### ISSUE TITLE
Добавить исключения в .gitignore

### ISSUE THREAD

**Issue by arkuz** [obscurezz/lesson_16#1]
У тебя прорвались в репу файлы кэша, файл лога и т.п.
- https://github.com/obscurezz/lesson_16/tree/main/models/__pycache__
- https://github.com/obscurezz/lesson_16/blob/main/logs/app.log

Можешь взять у меня файл, он очень большой, на все случаи жизни https://github.com/arkuz/skypro_hw_16/blob/main/.gitignore
Если в репу нужно положить пустую папку, то в ней нужно создать пустой файл .gitkeep

**Comment by obscurezz** [comment]
Ага, я тоже заметил. Спасибо за файл.
Я вчера первый день после отпуска, много мимо пропустил, решил быстренько нагнать программу просто)
